import {
  togglePassword,
  EmailDetail,
  BDetails,
  data1,
  search_result,
  PasswordDetail,
  data,
  loginResult,
  studentTable,
  search_name,
  SDetails,
  ScrollDetails,
  ProfileData,
  UpdateDatas,
  DecideState,
  EduState,
  Schostate,
} from "./RootReducer";
import { combineReducers } from "redux";
const reducer = combineReducers({
  togglePassword,
  EmailDetail,
  PasswordDetail,
  data,
  loginResult,
  studentTable,
  SDetails,
  search_name,
  search_result,
  data1,
  BDetails,
  ScrollDetails,
  ProfileData,
  UpdateDatas,
  DecideState,
  EduState,
  Schostate,
});
export default reducer;
